pull_request_rules:
  - name: auto squash dengan label ready-to-merge
    conditions:
      - base=main
      - label=ready-to-merge
    actions:
      comment:
        message: terima kasih sudah menambahkan config terbaru @{{author}} !
      label:
        add:
          - sudah di ditambahkan!
      merge:
        method: squash

  - name: menambahkan label
    conditions:
      - or:
        - files~=\.ini$
        - files~=\.sh$
    actions:
      label:
        add:
          - config baru !

