pull_request_rules:
  - name: auto squash dengan label ready-to-merge
    conditions:
      - base=main
      - label=ready-to-merge
    actions:
      comment:
        message: Terima kasih sudah menambahkan konfigurasi terbaru @{{author}}!
      label:
        add:
          - sudah ditambahkan!
      merge:
        method: squash

  - name: menambahkan label
    conditions:
      - or:
        - files~=\.ini$
        - files~=\.sh$
    actions:
      label:
        add:
          - konfigurasi baru!
